name: Lint & Test

on:
  push:
    branches:
      - 'main'
  pull_request_target:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  unit-test:
    name: Linting & Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.6'
      - name: Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - name: Run Tests
        run: make unit

# TODO: these are failing atm, enable once they pass
#  integ-test:
#    name: Integration Tests
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-go@v4
#        with:
#          go-version: '1.21.6'
#      - name: Run Tests
#        run: make integration
